default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: learning_sprint_tracker_development

test:
  <<: *default
  database: learning_sprint_tracker_test

production:
  <<: *default
  database: learning_sprint_tracker_production
  username: learning_sprint_tracker
  password: <%= ENV["LEARNING_SPRINT_TRACKER_DATABASE_PASSWORD"] %>

